### ISSUE TITLE
Link to User Profile instead of email

### ISSUE THREAD

**Issue by emptymalei** [timvink/mkdocs-git-authors-plugin#54]
Thank you for making such a useful plugin.

I am wondering if it is useful to provide an option to link to the user profile (e.g., GitHub profile) instead of email? 

For example, return

```
[
    {
    'name' : 'Jane Doe',
    'email' : 'jane@abc.com',
    'profile': 'https://github.com/jane',
    'last_datetime' : datetime.datetime(),
    'lines' : 200,
    'contribution' : '40.0%'
  }
]
```

Thanks.

**Comment by timvink** [comment]
Yeah it would be, but it's not as straightforward as it might seem.

Some challenges:

- `profile` could also be github, gitlab, bitbucket, azure devops, etc. 
- from the `git commit` logs, we can only find the `name` and `email` address. however, many users don't share their email publicly (including me), which means we cannot use the github API to find the profile. We could use `name` to search the github users api, but that does not guarantee a correct result. 
- We would need to make API calls, which means `mkdocs build` should have access to the internet. That's not always the case (f.e. when working behind a company proxy).

A more detailed analysis can be found in https://github.com/timvink/mkdocs-git-authors-plugin/issues/15

Because there is not an elegant solution design for this, I don't want to pick this up now..
