### ISSUE TITLE
Duplicate authors visible

### ISSUE THREAD

**Issue by mrmanc** [timvink/mkdocs-git-authors-plugin#59]
I can see a page with the same committer appearing twice in the authors provided by this plugin. I can see when hovering over that it is the same email address but some upper case letters in one variant, i.e. `jane.doe@domain.com` vs `Jane.Doe@domain.com`.

Would it be possible for the plugin to remove duplicate entries by ignoring case?

**Comment by mrmanc** [comment]
Thanks so much for a speedy change and release. Can confirm that has fixed the issue at my end. 🎉

**Comment by timvink** [comment]
No problem!

**Comment by jarkenau** [comment]
For me, there are duplicate authors on a page, because of a committer using different email with the same name. This is due to an author only getting identified by their email as stated here:
 https://github.com/timvink/mkdocs-git-authors-plugin/blob/96fb712c9d5635613f39dfb086978236fbb3f13a/mkdocs_git_authors_plugin/git/repo.py#L30-L48 
Is it possible we could also account for this?
