### ISSUE TITLE
Question/Suggestion: Authors summary on book level

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-authors-plugin#9]
I'm still working on the configurability of authors aggregation(https://github.com/timvink/mkdocs-git-authors-plugin/pull/4#issuecomment-591345656, 1.) but had to intermittently leave. This caused some rambling considerations while driving, and I had one more idea *[hopefully the last one for now since I really have to do some "content" work]*.

If I'm going to implement this additional idea it would be good to make some design decisions already for the aggregation code (instead of implementing just that one functionality and the *changing* the code only afterwards), so I'd like to have your opinion first, @timvink.

I would like to add a ninja template `git_authors_book_summary` that can be placed on a single page and will produce a summary of all authors present in the book rather than on the current page. This may (configurably) show the number of commits, the contribution percentage and the absolute number of lines the author has modified in the current state of the book (i.e. the aggregated `lines` count of all pages). In the future this could also provide some information about the book itself, e.g. total number of lines, number of pages, total size in characters (and words?), times of first and last commit etc. Although the latter might better be handled in a separate plugin.

The *main* design decision for this would be to retrieve the Git information not in `on_page_markdown` but in `on_files`. Here basically `get_authors()` will be called in its current implementation, and its results stored in a global `Authors` object. In the `on_page_markdown` we don't have to call Git anymore but just read out the stored data.
The aggregation of data for the *book* summary will only be done upon request, i.e. if the template is found, so there shouldn't be much overhead in this. There *will* be more memory usage because the information is stored globally and not only while retrieving the info per page, but I'm sure this is OK.

**Comment by timvink** [comment]
Not a bad idea! 

For me it's important to keep things as simple as possible for users. Advanced users should be able to extend a mkdocs theme using the variables that we expose via `git_authors` (a dict, see README).

For the users, we basically would just add just three variables to the dict: ` total_lines`,  `total_contribution`. In your case you could use those to make exactly what you need for your book. `total_commits` is tricky because when building docs via CI (github actions, gitlab runners) a shallow clone is made instead of pulling all commits. Easier to leave out. 

Not sure how to implement `total_lines` and `total_contribution` cleanly though.. I thought we could simply add to `plugin.py` on init an empty dict, e.g. `self.all_pages = {}`, and then update it for each `on_page_markdown`, e.g. `self._all_page[page_path] = author`. 

But then we would need [a mkdocs event](https://www.mkdocs.org/user-guide/plugins/#events) that after all pages have been processed, goes over it again and uses the fully populated `self.all_pages`. I don't yet see how `on_files` would solve that?

**Comment by uliska** [comment]
Maybe I'm mistaken, but we can iterate over all files in `on_files` and collect the data (actually all the Git blame data used in the `git_authors_summary` entries) and store them for the whole runtime.

If on any page the `git_authors_book_summary` template is encountered the corresponding HTML output can be generated from that stored data.

The regular `git_authors_summary` can also retrieve the data for the current page, which is of course indexed by path.

AFAICS there's no need to reiterate over the pages.

There would be some overhead only if the book consists of different themes, some with and some without the git authors display.

BTW: As mentioned in another comment I'm writing a few classes to replace the GitPython dependency, and these offer plenty of opportunity to manage that additional data, with (IISC) clean ways to add other features in the future.

**Comment by timvink** [comment]
I see, if `on_files` gives us a list of page paths, we can indeed collect all the `git blame` information once, save it in the plugin class, and then access the info `on_page_markdown`. 

I would still like to just update `git_authors` with extra variables, and not create more markdown tags (like `git_authors_book_summary`). 

Would you like to build this, or shall I work on it?

**Comment by uliska** [comment]
I have done some work today and will soon propose something for discussion (although maybe not immediate mergeable)
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by timvink** [comment]
We agreed having an author summary on the site level as well as the page level is a good idea. 
This functionality is now on the master branch (not yet op PyPi), currently as `{{ git_authors_list }}` but the naming will change (see discussion in #21) before next release.
